### ISSUE TITLE
Filtering equations incorrect in mgg_ssm::log_likelihood() (line 171)

### ISSUE THREAD

**Issue by zaczw** [helske/bssm#17]
See calculations in the photo attached. You wrote:

arma::mat K = Pt * Zt.t() * inv_cholF.t() * inv_cholF;

However, I think it should be:

arma::mat K = Pt * Zt.t() * inv_cholF * inv_cholF.t();

Thank you!

![filtering_incorrect](https://user-images.githubusercontent.com/7476244/36179456-fb89aa26-10e1-11e8-888e-f5d2aa1318aa.jpg)

**Comment by helske** [comment]
Thanks for catching this! I typically tend to use lower triangular version of the Cholesky decomposition (in which case the equations would be correct), but here I forgot to add the correct argument to `arma::chol`. But when fixing this issue I noticed another issue relating to multivariate models with partially missing observations, I will fix that at the same time as well, likely tomorrow.

**Comment by zaczw** [comment]
Thank you!
