### ISSUE TITLE
Installation from Github fails on Mac:  clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by sbgraves237** [helske/bssm#20]
With R 3.6.0 under macOS 10.14.4, 'devtools::install_github("helske/bssm")' produced the following:  

Downloading GitHub repo helske/bssm@master
✔  checking for file ‘/private/var/folders/mh/mrm_14nx19g13lsnj9zmvwjr0000gn/T/RtmpI8M1Qy/remotes57ff163932df/helske-bssm-70458ec/DESCRIPTION’ ...
─  preparing ‘bssm’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘bssm_0.1.7.tar.gz’
   
* installing *source* package ‘bssm’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ramcmc/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sitmo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c R_approx.cpp -o R_approx.o

clang: error: unsupported option '-fopenmp'

make: *** [R_approx.o] Error 1

NOTE:  This seemed quit similar to "Installation from Github fails on Mac #16", closed on 2017-11-13 with a solution posted.  However, that solution seems out of date, and I'm afraid to try it for fear I might create more problems for myself than I solve.  Thanks.

**Comment by helske** [comment]
Your clang compiler is apparently too old and/or wrong version, i.e. it does not support OpenMP. I'm not too familiar with macs, so I can't really help other than suggest installing newer version of clang or using gcc instead.

**Comment by sbgraves237** [comment]
A question to R-SIG-MAC produced a reply from Byron Ellis directing me to "https://cran.r-project.org/bin/macosx/tools/".  Than contained clang6, clang7, and clang8 plus versions of gfortran.  Clang6 is for R 3.5, clang7 for R 3.6, and clang8 is for R 3.7.  The current released version of R is 3.6, so I installed clang7, not the more recent clang8.  

    However, that was not enough to solve the problem.  I also had to add the following to "~/.Renviron":

        PATH="/usr/local/clang7/bin:${PATH}" 

Since "~/.Renviron" did not already exist, James Joseph Balamuta suggested I create it with "touch ~/.Renviron", then edit it with vi to add the required PATH.  After doing that, it worked.  Thanks to Joini for sharing what he knew about this.  Spencer Graves
