### ISSUE TITLE
mv_gssm missing from package

### ISSUE THREAD

**Issue by AEdlerfi** [helske/bssm#21]
Hi,

I just installed bssm from CRAN and the function mv_gssm is missing, despite being in the documentation. Should it be there?

I see it is in models.R, should I just download from github?

Thanks

Adam

**Comment by helske** [comment]
Oops, apparently I have deleted the `@export` line at some point. You can still access the function with `bssm:::mv_gssm`, but I will update the package to GitHub ASAP as well so you can access the function normal way.
