### ISSUE TITLE
can't use all fixed sd params in bsm_ng

### ISSUE THREAD

**Issue by khusmann** [helske/bssm#25]
Hello again,

I was trying to set fixed params for sd_level and sd_seasonal instead of priors, but it doesn't look like fixing both is allowed. (I was hoping to just solve for beta). For example:

```
model <- bsm_ng(Seatbelts[, "VanKilled"], distribution = "poisson",
  sd_level = halfnormal(0.01, 1),
  sd_seasonal = halfnormal(0.01, 1),
  beta = normal(0, 0, 10),
  xreg = Seatbelts[, "law"])

mcmc_bsm <- run_mcmc(model, iter = 5000, nsim=10)
```

works but:

```
model <- bsm_ng(Seatbelts[, "VanKilled"], distribution = "poisson",
  sd_level = 0.01,
  sd_seasonal = 0.01,
  beta = normal(0, 0, 10),
  xreg = Seatbelts[, "law"])

mcmc_bsm <- run_mcmc(model, iter = 5000, nsim=10)
```

gives error:

```
Error in nongaussian_da_mcmc(model, output_type, nsim, iter, burnin, thin, : Col::subvec(): indices out of bounds or incorrectly used
```

Thanks!

**Comment by helske** [comment]
Thanks, there seem to be some checks missing somewhere.

**Comment by helske** [comment]
Should be fixed now.

**Comment by khusmann** [comment]
Ah, thanks!

Is it not possible to have fixed params for the beta coefs as well? (I'm imagining a situation where all the coefs are known and we're just trying to smooth the alpha estimates)

**Comment by khusmann** [comment]
Right, that's what I would expect -- but when I try to fix beta I get:

```
Error in bsm_ng(y = sub_df, distribution = "binomial",  : 
  Prior for beta must be of class 'bssm_prior' or 'bssm_prior_list.
```

**Comment by helske** [comment]
Sorry, apparently it is not supported after all. :D In this case, you can just set the prior for beta so that you set the initial value to the known value of beta, and then run particle smoothing normally (prior doesn't have any effect there anyway). 

In general, if you need to have fixed beta but you have other unknown model parameters, you can write your model as general `ssm_ung` model and set the observational level intercept term `D = X %*% beta`.

**Comment by khusmann** [comment]
> Sorry, apparently it is not supported after all. :D

:) Is it worth adding as a feature request?

>  (prior doesn't have any effect there anyway).

Ah, interesting. Does this apply to all prior specifications? (That is, priors only are used in mcmc)

> In general, if you need to have fixed beta but you have other unknown model parameters, you can write your model as general ssm_ung

Ah! My next question was how to fix the slope in my model as well, but I think the general spec (ssm_ung) is what I've wanted all along. I'll dive in there and let you know if I have any questions.

**Comment by helske** [comment]
I'll reopen this issue so I will remember to add fixed beta option to bsm functions as well, I don't think it needs much work (I can't remember why I didn't

**Comment by helske** [comment]
Sure you can open a feature request, I (or someone) might add the option at some point, probably via the intercept term D (it is currently ignored in C++-side but wouldn't probably need much to make it work).

Yes, priors are only used during the MCMC, as they only affect the posterior which is not relevant for the filtering/smoothing (or maximum likelihood estimation using numerical optimization with help of `logLik` function).

For complex models, `ssm_ung` and its multivariate counterpart `ssm_mng` might be tricky as you need to manually define the corresponding system matrices. In those cases, you might want to check `as_bssm` function and the `KFAS` package.

**Comment by khusmann** [comment]
Ah, that all makes sense. Thanks for the replies!

I tried out the KFAS package but couldn't quite figure out the model building interface; manually defining the system matrices makes the most sense to me at this point. ssm_ung was exactly what I was looking for!

> probably via the intercept term D

I think this is the key for me. My challenge with ssm_ung was that I couldn't figure out how to add covariates, but since I have fixed betas I can just add those in as time-varying intercepts.

A quick check to make sure I understand: To have free betas (estimate covariate effects on observations) using `ssm_ung`, I would create a theta param that would manipulate the D matrix accordingly in a custom `update_fn` -- is that right?

> priors are only used during the MCMC, as they only affect the posterior which is not relevant for the filtering/smoothing

The MCMC estimates theta params though, which is relevant for smoothing right? After running the MCMC and estimating all the theta params, is there an easy way to insert those back into the model (similar to the way the `update_fn` does so that I can immediately smooth it? For example:

```
mcmc_result <- run_mcmc(model, ...)  # Estimate all free params
smooth_result <- smoother(mcmc_result) # Smooth model with estimated values for the free params
```

Cheers!

**Comment by helske** [comment]
> A quick check to make sure I understand: To have free betas (estimate covariate effects on observations) using `ssm_ung`, I would create a theta param that would manipulate the D matrix accordingly in a custom `update_fn` -- is that right?
> 
Yes exactly.

> The MCMC estimates theta params though, which is relevant for smoothing right? After running the MCMC and estimating all the theta params, is there an easy way to insert those back into the model (similar to the way the `update_fn` does so that I can immediately smooth it? For example:

The MCMC algorithms sample both theta and the states (depending on the argument `output_type`) so that the resulting posterior smoothing distribution of the states also takes into account the uncertainty of thetas.

**Comment by khusmann** [comment]
Gotcha. Thanks for your time to answer my questions!
