### ISSUE TITLE
Non-gaussian linear state model with continuous time

### ISSUE THREAD

**Issue by zjph602xtc** [helske/bssm#26]
Hi, I have a model that is a linear state model with non-gaussian response with continuous time.

I found that function 'ssm_nlg' seems to be able to handle linear (also, non-linear) **gaussian** with **continuous** time, while 'ssm_mng' can handle linear state model with **non-gaussian** response but **no continuous time**. 

I'm wondering whether it is possible to build a linear state model with **non-gaussian** response with **continuous** time. Is it possible to write C++ snippets in 'ssm_mng' function since the only difference is that I want continuous time. 

Thank you!

**Comment by helske** [comment]
You should be able to use `ssm_mng` for continuous time as well by defining the system matrices appropriately with the model updating function (see, e.g., examples in `?ssm_ulg`). In `ssm_nlg` the snippets define the system matrices such as Z_t for one time point t, whereas with other model types you define all Z_t1, ..., Z_tn matrices at once.

**Comment by helske** [comment]
Closing as solved, if not,  please re-open.
