### ISSUE TITLE
Stray Stats Std BS7.7

### ISSUE THREAD

**Issue by mpadge** [helske/bssm#30]
@helske I'm trying to figure out https://github.com/ropensci-review-tools/srr/issues/24, and note that you've got a standard BS7.7 in this line:

https://github.com/helske/bssm/blob/8c52ea3253af02c238f936de1618f37db61f0118/tests/testthat/test_mcmc.R#L3

But Bayesian standards only go up to BS7.4.That results in your code reporting 124 standards from a total of 123 General + Bayesian. I'll implement a catch for any non-existent standards in `srr`, and could you please correct that one in your code? Thanks!

**Comment by helske** [comment]
Thanks, I couldn't immediately figure out was it supposed to be something else or just some extra stuff so I just removed it for now.

**Comment by mpadge** [comment]
Great, thanks. HTML report still says 124 instead of 123 - is that okay with you? (I can update again if you really want.)

**Comment by helske** [comment]
Yes, that's ok.
