### ISSUE TITLE
Mat::init(): size is fixed and hence cannot be changed

### ISSUE THREAD

**Issue by Lxr-China** [helske/bssm#35]
![image](https://github.com/user-attachments/assets/1bdf3a0c-f6fc-4dec-894e-e71df37aef66)

**Comment by Lxr-China** [comment]
Hello, I intend to construct a nonlinear state space model using the BSSM package. N represents the number of economies, with the state vector having 11N dimensions and the observable vector having 2N dimensions. I have written C++ functions for Z, T, H, R, etc., based on the vignette template. However, the model encounters errors during the final runtime, as depicted in the figure. What should I do next? Thank you for your assistance.

**Comment by Lxr-China** [comment]
[ssm.zip](https://github.com/user-attachments/files/16736635/ssm.zip)
My CPP document and R script are both included in this compressed file.

**Comment by helske** [comment]
It sounds like one of your C++ functions tries to modify the size of the model matrices. Maybe try calling those C++ functions like `H_fn` separately from R with properly sized inputs and see which one causes the error, and then debug inside the function by adding some `Rcout` calls to spot the exact line.

**Comment by Lxr-China** [comment]
Thank you very much for your reply, which has provided me with insights into solving the problem. I wish you success in your work and happiness in your life.
