### ISSUE TITLE
How can I estimate the posterior distribution and point estimates of the state variables at each time point? 

### ISSUE THREAD

**Issue by Lxr-China** [helske/bssm#36]
Hello, I would like to ask you the following questions. If you could spare some time to reply, I would be extremely grateful!You are my savior!!You are my savior!!
﻿
1、Background of the problem:
(1) We have a nonlinear Gaussian state space model as follows:
The observation vector has 2 dimensions, the state vector has 6 dimensions, and the observation data comprises 31 time points.
﻿
(2) Model estimation method:
We use either pseudo-marginal MCMC or the delayed acceptance version of PMCMC to obtain more accurate results.
﻿
(3) Model objective: To estimate the values of state variables at various time points.
﻿
2、My question:
I have already used the function runmcmc(·) to output mcmcoutput. How can I estimate the posterior distribution and point estimates of the state variables at each time point? For example, how to estimate the posterior distribution of the fifth state variable at the third time point, and how to obtain this posterior distribution from the mcmc_output? Is there a function in the BSSM software package that can solve this problem?
﻿
I am looking forward to your reply very much. You are my savior!!

**Comment by helske** [comment]
There are some examples in the [bssm paper](https://journal.r-project.org/archive/2021/RJ-2021-103/index.html) and in ` ?as.data.frame.mcmc_output`. Basically you can do
```
data("poisson_series")
model <- bsm_ng(y = poisson_series, 
sd_slope = halfnormal(0.1, 0.1), 
sd_level = halfnormal(0.1, 1),
  distribution = "poisson")
  
out <- run_mcmc(model, iter = 2000, particles = 10)
posterior_of_states <- as.data.frame(out, variable = "states")
str(posterior_of_states)
'data.frame':	202000 obs. of  5 variables:
 $ iter    : num  1001 1002 1003 1004 1005 ...
 $ value   : num  -0.3084 -0.0555 -0.0555 -0.0555 -0.4753 ...
 $ variable: chr  "level" "level" "level" "level" ...
 $ time    : num  1 1 1 1 1 1 1 1 1 1 ...
 $ weight  : num  0.735 0.972 0.972 0.972 1.047 ...
```
From which you can compute or visualize what ever you want. Or you can use
```
summary(out, variable = "states")
```
which directly gives you posterior means, standard deviations and quantiles.

For specific time point you can also use argument `times` in both functions, e.g.,
```
summary(out, variable = "states", times = 3, states = 2)
  variable time       Mean         SD       2.5%     97.5%
1    slope    3 0.02067069 0.05601965 -0.1087237 0.1201469
```

**Comment by Lxr-China** [comment]
Thank you! I'll try it.

**Comment by Lxr-China** [comment]
[R,C++,xts_data.zip](https://github.com/user-attachments/files/17270763/R.C%2B%2B.xts_data.zip)

Hello, here are the issues I am facing:
![image](https://github.com/user-attachments/assets/087e5b59-2a2e-470e-8ee7-854bb1cbc8b2)
error：Initial log-likelihood is not finite.
May I ask what is the general reason for this situation? Thank you！
The compressed file contains R script, CPP code, and data xts_data. i look forward to your reply.

**Comment by helske** [comment]
I do not have time to go through your zip file. There are multiple reasons why you might encounter nonfinite log-likelihood, for example it could be due to poor match of your data/model/prior/parameters, incorrectly defined model, or the bootstrap particle filter fails for example due to too small number of particles. Try getting logLik(model, particles = x, method = "bsf") work first to get ideas where issues might arise.

**Comment by Lxr-China** [comment]
Thank you very much for your reply, which provided me with a solution to the problem. Thank you .
